### PR TITLE
add type annotation info to spec

### PR DESCRIPTION
**Pull request by zkat**
Fixes: https://github.com/kdl-org/kdl/issues/106

### CODE REVIEW

**Comment by tabatkins** [comment]
I voted for `tag>value` in the Twitter poll but immediately changed my mind - this `(tag)value` syntax is way better.

Reviewing the commit, +1 from me. The only thing I'm not happiest about is the reserved `uri` type; the distinction between URI and URL is academic and worthless in practice, and "URL" has decidedly won in common parlance.

**Comment by passcod** [comment]
Are non-bare identifiers valid as types?

```
node val=("birth date")1987
```

**Comment by tabatkins** [comment]
Yes:

```
identifier := string | bare-identifier
[...]
type := '(' identifier ')'
```

**Comment by passcod** [comment]
Sorry, wording: I meant, should they be?

**Comment by tabatkins** [comment]
Ah, kk. Yeah, why shouldn't they be? Allowing strings doesn't affect the readability, and the feature itself doesn't seem to have any reason to tie itself to the bare-ident restrictions.

**Comment by zkat** [comment]
string-based identifiers are acceptable intentionally. As Tab says, there doesn't seem to be any reason to limit it to bare identifiers.

**Comment by zkat** [comment]
@tabatkins the reason for calling it "uri" is because that's what JSON Schema calls it, and thus what KDL Schema calls it. I'd be more than happy to have _both_ `url` and `uri`, though, because I agree with you, but we should do that as a separate PR because the Schema spec needs to be updated too.

**Pull request merged**
