### PR TITLE
reword interaction multiline + whitespace escape

### PR DESCRIPTION
**Pull request by bgotink**
Trying to resolve https://github.com/kdl-org/kdl/pull/434#discussion_r1886757547

### CODE REVIEW

**Review by zkat — APPROVED** [review]
I like this, but having others chime in would be good.

**Comment by bgotink** [comment]
@tjol I gave it another try, could you take another look?

**Comment by tjol** [comment]
I like it!

**Comment by zkat** [comment]
I like this a lot, too! Thanks for taking the time!

**Pull request merged**
